title: Pranav's Blog
description: Pranav's blog on art, philosophy, physics, ai, books, travel, and life
baseurl: "" # Set to "/repo-name" if hosting in a project repository
url: "https://github.com/pranavRajmane/Fermats-next-theorem" # Replace with your GitHub Pages URL
theme: # Optional: Use a theme or leave blank for custom
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /blog/:title